# Generated by Django 5.2.17 on 2026-09-14 18:59

import apps.core.money
import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySales",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_date", models.DateField()),
                (
                    "money_taken_pesewas",
                    apps.core.money.PesewasField(
                        help_text="Money taken — gross cash through the till. Not revenue."
                    ),
                ),
                ("covers", models.IntegerField(default=0)),
                ("orders_closed", models.IntegerField(default=0)),
                ("orders_voided", models.IntegerField(default=0)),
                (
                    "void_value_pesewas",
                    apps.core.money.PesewasField(
                        default=0, help_text="Integer pesewas (GH₵ x 100)."
                    ),
                ),
                (
                    "discount_pesewas",
                    apps.core.money.PesewasField(
                        default=0, help_text="Integer pesewas (GH₵ x 100)."
                    ),
                ),
                ("cash_variance_pesewas", models.IntegerField(default=0)),
                ("computed_at", models.DateTimeField()),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "daily sales",
                "db_table": "daily_sales",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("restaurant", "business_date"), name="uniq_daily_sales_per_date"
                    )
                ],
            },
        ),
    ]
