# Generated by Django 5.2.17 on 2026-09-14 18:59

import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("IN_PROGRESS", "In Progress"), ("DONE", "Done")],
                        default="IN_PROGRESS",
                        max_length=16,
                    ),
                ),
                ("response_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "idempotency_keys",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("restaurant", "key"), name="uniq_idempotency_key"
                    )
                ],
            },
        ),
    ]
