# Generated by Django 5.2.17 on 2026-09-14 18:59

import apps.core.money
import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("floor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_date", models.DateField(blank=True, null=True)),
                (
                    "order_number",
                    models.IntegerField(
                        blank=True, help_text="NULL while DRAFT. Gaps are an alarm.", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PREPARING", "Preparing"),
                            ("READY", "Ready"),
                            ("SERVED", "Served"),
                            ("CLOSED", "Closed"),
                            ("VOIDED", "Voided"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "subtotal_pesewas",
                    apps.core.money.PesewasField(
                        default=0, help_text="Integer pesewas (GH₵ x 100)."
                    ),
                ),
                (
                    "discount_pesewas",
                    apps.core.money.PesewasField(
                        default=0, help_text="Integer pesewas (GH₵ x 100)."
                    ),
                ),
                (
                    "total_pesewas",
                    apps.core.money.PesewasField(
                        default=0, help_text="subtotal − discount. This is the whole calculation."
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("WAITER", "Waiter"),
                            ("GUEST_TABLET", "Guest Tablet"),
                            ("GUEST_QR", "Guest Qr"),
                        ],
                        default="WAITER",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("served_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "authorised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "placed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="floor.tablesession",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_date", models.DateField()),
                ("next_number", models.IntegerField(default=1)),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "order_counters",
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seq",
                    models.BigIntegerField(
                        help_text="Per restaurant, gapless, assigned under an advisory lock."
                    ),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        choices=[
                            ("ORDER", "ORDER"),
                            ("SESSION", "SESSION"),
                            ("SHIFT", "SHIFT"),
                            ("MENU_ITEM", "MENU_ITEM"),
                            ("DEVICE", "DEVICE"),
                            ("STAFF", "STAFF"),
                        ],
                        max_length=16,
                    ),
                ),
                ("aggregate_id", models.UUIDField()),
                ("order_id", models.UUIDField(blank=True, null=True)),
                ("event_type", models.CharField(max_length=40)),
                ("payload", models.JSONField(default=dict)),
                (
                    "actor_role",
                    models.CharField(
                        choices=[
                            ("WAITER", "WAITER"),
                            ("KITCHEN", "KITCHEN"),
                            ("CASHIER", "CASHIER"),
                            ("MANAGER", "MANAGER"),
                            ("OWNER", "OWNER"),
                            ("GUEST", "GUEST"),
                            ("SYSTEM", "SYSTEM"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64, null=True)),
                ("idempotency_key", models.UUIDField()),
                (
                    "client_created_at",
                    models.DateTimeField(help_text="What the device claimed. Audit only."),
                ),
                (
                    "created_at",
                    models.DateTimeField(help_text="What the server knows. Authoritative."),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "authorised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.device",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "order_events",
                "ordering": ["seq"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "menu_item_id",
                    models.UUIDField(
                        help_text="Reference only. Name and price below are the truth for this line."
                    ),
                ),
                ("name_snapshot", models.CharField(max_length=120)),
                (
                    "unit_price_pesewas",
                    apps.core.money.PesewasField(help_text="Integer pesewas (GH₵ x 100)."),
                ),
                ("prep_station", models.CharField(max_length=16)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "modifiers",
                    models.JSONField(
                        default=list, help_text="[{id, name, price_pesewas}] — snapshots too."
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("course", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PREPARING", "Preparing"),
                            ("READY", "Ready"),
                            ("SERVED", "Served"),
                            ("VOIDED", "Voided"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "line_total_pesewas",
                    apps.core.money.PesewasField(
                        help_text="(unit_price + Σ modifier prices) × quantity"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant", "status", "-created_at"], name="orders_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["restaurant", "session"], name="orders_session_idx"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order_number__isnull", False)),
                fields=("restaurant", "business_date", "order_number"),
                name="uniq_order_number_per_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal_pesewas__gte", 0)), name="order_subtotal_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_pesewas__gte", 0)), name="order_discount_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_pesewas__gte", 0)), name="order_total_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="ordercounter",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "business_date"), name="uniq_order_counter_per_date"
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(fields=["restaurant", "idempotency_key"], name="oe_idem_idx"),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(fields=["restaurant", "order_id", "seq"], name="oe_order_seq_idx"),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["restaurant", "aggregate_type", "aggregate_id", "seq"],
                name="oe_aggregate_seq_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(fields=["restaurant", "-created_at"], name="oe_created_idx"),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["restaurant", "event_type", "-created_at"], name="oe_type_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["restaurant", "actor", "-created_at"], name="oe_actor_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderevent",
            constraint=models.UniqueConstraint(fields=("restaurant", "seq"), name="uniq_seq"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["restaurant", "order"], name="order_items_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="order_item_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price_pesewas__gte", 0)),
                name="order_item_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_total_pesewas__gte", 0)),
                name="order_item_total_non_negative",
            ),
        ),
    ]
