# Generated by Django 5.2.17 on 2026-09-14 18:59

import apps.core.money
import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "menu_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("image", models.ImageField(blank=True, null=True, upload_to="menu/")),
                (
                    "price_pesewas",
                    apps.core.money.PesewasField(
                        help_text="What the guest pays. Tax-inclusive. Integer pesewas."
                    ),
                ),
                (
                    "prep_station",
                    models.CharField(
                        choices=[("KITCHEN", "Kitchen"), ("GRILL", "Grill"), ("BAR", "Bar")],
                        default="KITCHEN",
                        max_length=16,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="The 86 switch. Projection of ITEM_86ED / ITEM_RESTORED.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False = retired from the menu. Never deleted."
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="menu.menucategory",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "menu_items",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ModifierGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "selection",
                    models.CharField(choices=[("ONE", "One"), ("MANY", "Many")], max_length=4),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "modifier_groups",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Modifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "price_pesewas",
                    apps.core.money.PesewasField(default=0, help_text="0 for free choices."),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modifiers",
                        to="menu.modifiergroup",
                    ),
                ),
            ],
            options={
                "db_table": "modifiers",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemModifierGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modifier_links",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_links",
                        to="menu.modifiergroup",
                    ),
                ),
            ],
            options={
                "db_table": "menu_item_modifier_groups",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddConstraint(
            model_name="menuitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_pesewas__gte", 0)), name="menu_item_price_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="modifier",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_pesewas__gte", 0)), name="modifier_price_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="menuitemmodifiergroup",
            constraint=models.UniqueConstraint(
                fields=("menu_item", "group"), name="uniq_menu_item_modifier_group"
            ),
        ),
    ]
