# Generated by Django 5.2.17 on 2026-09-14 18:59

import apps.core.uuid7
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("timezone", models.CharField(default="Africa/Accra", max_length=64)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("day_cutover_hour", models.PositiveSmallIntegerField(default=4)),
                ("service_start", models.TimeField(default="11:00")),
                ("service_end", models.TimeField(default="23:00")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "restaurants",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("token_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("enrolment_code", models.CharField(blank=True, max_length=16, null=True)),
                ("enrolment_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allowed_roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("WAITER", "WAITER"),
                                ("KITCHEN", "KITCHEN"),
                                ("CASHIER", "CASHIER"),
                                ("MANAGER", "MANAGER"),
                                ("OWNER", "OWNER"),
                                ("GUEST", "GUEST"),
                                ("PRINTER", "PRINTER"),
                            ],
                            max_length=16,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "devices",
                "indexes": [models.Index(fields=["token_hash"], name="devices_token_hash_idx")],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("WAITER", "WAITER"),
                            ("KITCHEN", "KITCHEN"),
                            ("CASHIER", "CASHIER"),
                            ("MANAGER", "MANAGER"),
                            ("OWNER", "OWNER"),
                        ],
                        max_length=16,
                    ),
                ),
                ("pin_hash", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Django user for owner login and admin. OWNER / MANAGER only.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "staff",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("email__isnull", False)),
                        fields=("restaurant", "email"),
                        name="uniq_staff_email_per_restaurant",
                    )
                ],
            },
        ),
    ]
