/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/authorise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/authorise — manager/owner PIN → single-use authorisation token. */
        post: operations["auth_authorise_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/logout — revoke staff jti and/or end owner session. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/owner/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/owner/login — email + password; TOTP still required. */
        post: operations["auth_owner_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/owner/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /auth/owner/me — proves owner session + TOTP (middleware principal). */
        get: operations["auth_owner_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/owner/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/owner/totp — verify TOTP and mark the session OTP-verified. */
        post: operations["auth_owner_totp_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/pin — device + staff PIN → staff JWT. */
        post: operations["auth_pin_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/enrol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /devices/enrol — exchange a one-time enrolment code for a device token. */
        post: operations["devices_enrol_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /devices/me — device label, roles, staff list for the PIN pad. */
        get: operations["devices_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll events (SSE fallback)
         * @description GET /api/v1/events?since=<seq>&limit=200 — polling fallback with the same envelopes as the stream.
         */
        get: operations["events_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/sessions/{qr_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /guest/sessions/{qr_token} — guest phone via table QR; table must have an open session. */
        post: operations["guest_sessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /guest/sessions/{id} — guest may only read their own open session (404 otherwise). */
        get: operations["guest_sessions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/guest-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /sessions/{id}/guest-token — waiter hands the tablet to the guest. */
        post: operations["sessions_guest_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_authorise_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key": string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key": string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_owner_login_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key": string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_owner_me_retrieve: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_owner_totp_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key": string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_pin_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key": string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    devices_enrol_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key": string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    devices_me_retrieve: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    events_retrieve: {
        parameters: {
            query?: {
                /** @description Max events (default 200, max 1000). */
                limit?: number;
                /** @description Last seq seen. Returns events with seq > since. */
                since?: number;
            };
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    guest_sessions_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key": string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
            };
            path: {
                qr_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guest_sessions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sessions_guest_token_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key": string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
