/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/authorise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/authorise — manager/owner PIN → single-use authorisation token. */
        post: operations["auth_authorise_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/logout — revoke staff jti and/or end owner session. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/owner/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/owner/login — email + password; TOTP still required. */
        post: operations["auth_owner_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/owner/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /auth/owner/me — proves owner session + TOTP (middleware principal). */
        get: operations["auth_owner_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/owner/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/owner/totp — verify TOTP and mark the session OTP-verified. */
        post: operations["auth_owner_totp_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/pin — device + staff PIN → staff JWT. */
        post: operations["auth_pin_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bills/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /bills/open — the cashier's board: what is still owing, and what can be paid yet. */
        get: operations["bills_open"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/enrol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /devices/enrol — exchange a one-time enrolment code for a device token. */
        post: operations["devices_enrol_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /devices/me — device label, roles, staff list for the PIN pad.
         *
         *     Answers to the device token alone: the PIN pad needs the staff list before anyone has signed in.
         *     A staff bearer, if sent, must still be valid (a revoked or foreign token is 401). Guests are 403.
         */
        get: operations["devices_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll events (SSE fallback)
         * @description `last_seq` is the highest seq scanned, including events this role may not see — always send it back as `since`. `has_more` means call again immediately.
         */
        get: operations["events_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full menu for a guest token
         * @description GET /guest/menu — the same menu on the sandboxed guest router (guest token only, throttled).
         */
        get: operations["guest_menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["guest_orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["guest_orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/orders/{order_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["guest_orders_items_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/orders/{order_id}/items/{item_id}/modify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["guest_orders_items_modify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/orders/{order_id}/items/{item_id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["guest_orders_items_remove_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/orders/{order_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["guest_orders_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/sessions/{qr_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /guest/sessions/{qr_token} — guest phone via table QR; table must have an open session. */
        post: operations["guest_sessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /guest/sessions/{id} — guest may only read their own open session (404 otherwise). */
        get: operations["guest_sessions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kds/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["kds_tickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full menu (categories → items → modifier groups → modifiers)
         * @description GET /menu — full active menu tree with ETag / If-None-Match.
         */
        get: operations["menu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/items/{item_id}/86": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 86 a menu item (mark unavailable) */
        post: operations["menu_item_86"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/items/{item_id}/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change a menu item price (auth required during service)
         * @description POST /menu/items/{id}/price.
         *
         *     During service hours, requires manager authorisation with purpose
         *     PRICE_CHANGE_IN_SERVICE. Outside service hours, no authorisation block.
         */
        post: operations["menu_item_price"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/items/{item_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an 86'd menu item */
        post: operations["menu_item_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_ack_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/comp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_comp_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/discount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_discount_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/fire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Phase 4 — registered so the route exists; returns 501. */
        post: operations["orders_fire_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_items_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/items/{item_id}/modify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_items_modify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/items/{item_id}/price-override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_items_price_override_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/items/{item_id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_items_ready_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/items/{item_id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_items_remove_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/items/{item_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_items_start_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_ready_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/serve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_serve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{order_id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orders_void_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{payment_id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["payments_void"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/print/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a printed sales record
         * @description Appends `RECEIPT_REQUESTED` so the print bridge produces the guest's copy. Every request is logged, and `reprint` is true when paper was already produced for this bill. The sales record carries no tax line and no fiscal reference (ADR-0005).
         */
        post: operations["print_receipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sessions_open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/bill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sessions_bill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sessions_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/guest-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /sessions/{id}/guest-token — waiter hands the tablet to the guest. */
        post: operations["sessions_guest_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sessions_record_payment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reopening a settled bill is the classic leak, so it needs a manager and tells the owner. */
        post: operations["sessions_reopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["shifts_open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shifts/{shift_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["shifts_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shifts/{shift_id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Cash moving with no sale behind it. Always a manager's PIN and a reason. */
        post: operations["shifts_movement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shifts/{shift_id}/z-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["shifts_z_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shifts/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /shifts/current — the caller's open shift, or null so the UI shows the open-shift screen. */
        get: operations["shifts_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tables_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddItemInputRequest: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            menu_item_id: string;
            quantity: number;
            modifier_ids?: string[];
            /** @default  */
            notes: string;
            /** @default 1 */
            course: number;
        };
        AuthoriseInputRequest: {
            pin: string;
            /**
             * @description * `VOID_AFTER_ACK` - VOID_AFTER_ACK
             *     * `DISCOUNT` - DISCOUNT
             *     * `COMP` - COMP
             *     * `PRICE_OVERRIDE` - PRICE_OVERRIDE
             *     * `REOPEN` - REOPEN
             *     * `DRAWER_MOVEMENT` - DRAWER_MOVEMENT
             *     * `PAYMENT_VOID` - PAYMENT_VOID
             *     * `PRICE_CHANGE_IN_SERVICE` - PRICE_CHANGE_IN_SERVICE
             * @enum {string}
             */
            purpose: "VOID_AFTER_ACK" | "DISCOUNT" | "COMP" | "PRICE_OVERRIDE" | "REOPEN" | "DRAWER_MOVEMENT" | "PAYMENT_VOID" | "PRICE_CHANGE_IN_SERVICE";
        };
        CloseShiftInputRequest: {
            declared_cash_pesewas: number;
            /** @default  */
            note: string;
        };
        CompInputRequest: {
            reason_code?: string;
            /** @default  */
            note: string;
        };
        DiscountInputRequest: {
            /**
             * @description * `PERCENT` - PERCENT
             *     * `AMOUNT` - AMOUNT
             * @enum {string}
             */
            kind: "PERCENT" | "AMOUNT";
            value: number;
            reason_code?: string;
            /** @default  */
            note: string;
        };
        DrawerMovementInputRequest: {
            /**
             * @description * `NO_SALE` - No Sale
             *     * `PAID_OUT` - Paid Out
             *     * `PAID_IN` - Paid In
             * @enum {string}
             */
            kind: "NO_SALE" | "PAID_OUT" | "PAID_IN";
            /** @default 0 */
            amount_pesewas: number;
            reason_code?: string;
            /** @default  */
            note: string;
        };
        EnrolDeviceInputRequest: {
            enrolment_code: string;
        };
        GuestTokenInputRequest: {
            /**
             * @description * `guest` - guest
             * @default guest
             * @enum {string}
             */
            mode: "guest";
        };
        ModifyItemInputRequest: {
            quantity?: number;
            modifier_ids?: string[];
            notes?: string;
            course?: number;
        };
        OpenOrderInputRequest: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            session_id: string;
        };
        OpenSessionInputRequest: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            table_id: string;
            party_size?: number | null;
        };
        OpenShiftInputRequest: {
            /** Format: uuid */
            id: string;
            opening_float_pesewas: number;
        };
        PinLoginInputRequest: {
            /** Format: uuid */
            staff_id: string;
            pin: string;
        };
        PriceChangeInputRequest: {
            price_pesewas: number;
        };
        PriceOverrideInputRequest: {
            unit_price_pesewas: number;
            reason_code?: string;
            /** @default  */
            note: string;
        };
        RecordPaymentInputRequest: {
            /** Format: uuid */
            id: string;
            /**
             * @description * `CASH` - Cash
             *     * `MOMO_MTN` - Momo Mtn
             *     * `MOMO_TELECEL` - Momo Telecel
             *     * `MOMO_AT` - Momo At
             *     * `CARD` - Card
             *     * `BANK` - Bank
             * @enum {string}
             */
            method: "CASH" | "MOMO_MTN" | "MOMO_TELECEL" | "MOMO_AT" | "CARD" | "BANK";
            amount_pesewas: number;
            tendered_pesewas?: number | null;
            external_reference?: string | null;
            /** Format: uuid */
            order_id?: string | null;
        };
        ReopenSessionInputRequest: {
            reason_code?: string;
            /** @default  */
            note: string;
        };
        RequestReceiptInputRequest: {
            /**
             * Format: uuid
             * @description The bill to print a sales record for.
             */
            session_id: string;
        };
        VoidInputRequest: {
            reason_code: string;
            /** @default  */
            note: string;
        };
        VoidPaymentInputRequest: {
            reason_code?: string;
            /** @default  */
            note: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_authorise_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoriseInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_owner_login_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_owner_me_retrieve: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_owner_totp_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_pin_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinLoginInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bills_open: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    devices_enrol_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrolDeviceInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    devices_me_retrieve: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    events_retrieve: {
        parameters: {
            query?: {
                /** @description Max events scanned (default 200, max 1000). */
                limit?: number;
                /** @description Last seq seen. Returns events with seq > since. */
                since?: number;
            };
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    guest_menu_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description No response body */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guest_orders_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenOrderInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guest_orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guest_orders_items_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guest_orders_items_modify_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
            };
            path: {
                item_id: string;
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ModifyItemInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guest_orders_items_remove_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
            };
            path: {
                item_id: string;
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guest_orders_submit_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guest_sessions_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
            };
            path: {
                qr_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guest_sessions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    kds_tickets: {
        parameters: {
            query?: {
                /** @description Show only lines for one prep station: KITCHEN, GRILL or BAR. */
                station?: "BAR" | "GRILL" | "KITCHEN";
            };
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    menu_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description No response body */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    menu_item_86: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    menu_item_price: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceChangeInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    menu_item_restore: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    orders_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenOrderInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_retrieve: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_ack_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_comp_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CompInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_discount_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscountInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_fire_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_items_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_items_modify_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                item_id: string;
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ModifyItemInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_items_price_override_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                item_id: string;
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceOverrideInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_items_ready_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                item_id: string;
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_items_remove_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                item_id: string;
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_items_start_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                item_id: string;
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_ready_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_serve_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_submit_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orders_void_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payments_void: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["VoidPaymentInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    print_receipt: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestReceiptInputRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sessions_open: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenSessionInputRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sessions_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sessions_bill: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sessions_close: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sessions_guest_token_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GuestTokenInputRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sessions_record_payment: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordPaymentInputRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sessions_reopen: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReopenSessionInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    shifts_open: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenShiftInputRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    shifts_close: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                shift_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseShiftInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    shifts_movement: {
        parameters: {
            query?: never;
            header?: {
                /** @description **Required by the server.** Client-generated UUIDv7, unique per command. Replays return the original response with `Idempotent-Replayed: true`. */
                "Idempotency-Key"?: string;
                /** @description The device's clock at send time (ISO 8601). Stored for audit; never used for ordering. */
                "X-Client-Time"?: string;
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                shift_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrawerMovementInputRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    shifts_z_report: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path: {
                shift_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    shifts_current: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    tables_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description Enrolled device token. Required for every staff request. */
                "X-Device-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
