# Generated by Django 5.2.17 on 2026-09-14 18:59

import apps.core.money
import apps.core.uuid7
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("floor", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opening_float_pesewas",
                    apps.core.money.PesewasField(help_text="Integer pesewas (GH₵ x 100)."),
                ),
                (
                    "declared_cash_pesewas",
                    apps.core.money.PesewasField(
                        blank=True, help_text="What the cashier counted.", null=True
                    ),
                ),
                (
                    "expected_cash_pesewas",
                    apps.core.money.PesewasField(
                        blank=True,
                        help_text="float + Σ cash payments − Σ paid out + Σ paid in",
                        null=True,
                    ),
                ),
                (
                    "variance_pesewas",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("declared_cash_pesewas"),
                            "-",
                            models.F("expected_cash_pesewas"),
                        ),
                        output_field=models.IntegerField(),
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="accounts.staff",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "shifts",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MOMO_MTN", "Momo Mtn"),
                            ("MOMO_TELECEL", "Momo Telecel"),
                            ("MOMO_AT", "Momo At"),
                            ("CARD", "Card"),
                            ("BANK", "Bank"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount_pesewas",
                    apps.core.money.PesewasField(help_text="Integer pesewas (GH₵ x 100)."),
                ),
                (
                    "tendered_pesewas",
                    apps.core.money.PesewasField(blank=True, help_text="Cash only.", null=True),
                ),
                (
                    "change_pesewas",
                    apps.core.money.PesewasField(blank=True, help_text="Cash only.", null=True),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="MoMo transaction id, keyed by the cashier.",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only when paying one round explicitly.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="floor.tablesession",
                    ),
                ),
                (
                    "void_authorised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.shift",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="DrawerMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("NO_SALE", "No Sale"),
                            ("PAID_OUT", "Paid Out"),
                            ("PAID_IN", "Paid In"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount_pesewas",
                    apps.core.money.PesewasField(default=0, help_text="0 for NO_SALE"),
                ),
                ("reason_code", models.CharField(max_length=64)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("recorded_at", models.DateTimeField()),
                (
                    "authorised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="payments.shift",
                    ),
                ),
            ],
            options={
                "db_table": "drawer_movements",
            },
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True)),
                fields=("cashier",),
                name="one_open_shift_per_cashier",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(
                condition=models.Q(("opening_float_pesewas__gte", 0)),
                name="shift_float_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["restaurant", "shift"], name="payments_shift_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["restaurant", "session"], name="payments_session_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["restaurant", "-recorded_at"], name="payments_recorded_idx"),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_pesewas__gt", 0)), name="payment_amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="drawermovement",
            index=models.Index(fields=["restaurant", "shift"], name="drawer_movements_shift_idx"),
        ),
        migrations.AddConstraint(
            model_name="drawermovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_pesewas__gte", 0)), name="drawer_movement_non_negative"
            ),
        ),
    ]
