# Generated by Django 5.2.17 on 2026-09-14 18:59

import apps.core.money
import apps.core.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(help_text="'7', '12A', 'Terrace 2'", max_length=16)),
                ("seats", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "qr_token",
                    models.CharField(
                        help_text="Printed on the table QR for guest-phone ordering.", max_length=64
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "tables",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="TableSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("party_size", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bill_total_pesewas",
                    apps.core.money.PesewasField(
                        default=0, help_text="Σ non-voided orders.total_pesewas"
                    ),
                ),
                (
                    "paid_pesewas",
                    apps.core.money.PesewasField(
                        default=0, help_text="Σ non-voided payments.amount_pesewas"
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.restaurant",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="floor.table",
                    ),
                ),
            ],
            options={
                "db_table": "table_sessions",
            },
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "number"), name="uniq_table_number_per_restaurant"
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(fields=("qr_token",), name="uniq_table_qr_token"),
        ),
        migrations.AddIndex(
            model_name="tablesession",
            index=models.Index(fields=["restaurant", "closed_at"], name="sessions_open_idx"),
        ),
        migrations.AddConstraint(
            model_name="tablesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True)),
                fields=("table",),
                name="one_open_session_per_table",
            ),
        ),
    ]
